import { Poppins } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/common/navbar/NavBar";
import Script from "next/script";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script async src="https://www.googletagmanager.com/gtag/js?id=AW-16906626077">
        </script>

        <Script
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());

            gtag('config', 'AW-16906626077');
          `,
          }}
        />
      </head>

      <body
        className={`${poppins.variable} antialiased`}
      >
        <Navbar />
        <main className="pb-32">
          {children}
        </main>
      </body>
    </html>
  );
}
